### ISSUE TITLE
handleInvalid param not retained across serialization/deserialization of spark StringIndexer

### ISSUE THREAD

**Issue by varunkrmodi** [combust/mleap#180]
When serialising a **StringIndexer** transformer in spark, and reloading it back as a **StringIndexer** spark transformer using the following Bundle.ML code : 
https://github.com/combust/mleap/blob/master/mleap-spark/src/main/scala/org/apache/spark/ml/bundle/ops/feature/StringIndexerOp.scala
 
The value of the param handleInvalid (https://github.com/apache/spark/blob/v2.0.2/mllib/src/main/scala/org/apache/spark/ml/feature/StringIndexer.scala#L75) of the serialised spark transformer is not retained.

**Comment by hollinwilkins** [comment]
@varunkrmodi Hey,

I am taking a look at this right now, and there are two modes of operation:
1. error
2. skip

Because of the way that MLeap runtime works, the only one that really makes sense for scoring is error.

I'm going to implement this so that the handle_invalid field is set, but only does something for Spark.
