### ISSUE TITLE
Problem with airbnb.avro.zip

### ISSUE THREAD

**Issue by clocklear** [combust/mleap#196]
URL: https://s3-us-west-2.amazonaws.com/mleap-demo/datasources/airbnb.avro.zip

Doesn't appear to have a valid, complete zip file.  

```
~/Downloads » ls -al airbnb.avro.zip
-rw-r--r--@ 1 clocklear  staff  67108864 Apr 25 14:15 airbnb.avro.zip
```

```
~/Downloads » unzip airbnb.avro.zip
Archive:  airbnb.avro.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of airbnb.avro.zip or
        airbnb.avro.zip.zip, and cannot find airbnb.avro.zip.ZIP, period.
```

**Comment by ancasarb** [comment]
@clocklear I had the same issue and I don't remember for sure because it was a while ago, but I think I managed to find the airbnb.avro on the old mleap github repo somewhere I think. I couldn't attach it here directly because it's bigger than 10mb, but below is a google drive link to the avro file

https://drive.google.com/file/d/0B6QOjABLM2azeHFPbHJub3FvUnc/view?usp=sharing

@hollinwilkins could you please help update the file into the S3 bucket? thank you!

**Comment by clocklear** [comment]
Thanks @ancasarb!

**Comment by seme0021** [comment]
@clocklear @ancasarb I updated the demo [notebook](https://github.com/combust/mleap-demo/blob/master/notebooks/PySpark%20-%20AirBnb.ipynb) to point to the `.avro` directly instead of the `.zip` file.

Lmk if it doesn't work.

**Comment by clocklear** [comment]
Direct avro file appears to work fine.  Thanks for following up.

**Comment by ancasarb** [comment]
@seme0021 thank you, that worked fine!
