### ISSUE TITLE
Need to a workable example

### ISSUE THREAD

**Issue by ltang** [combust/mleap#20]
Hi, 

Just want to say this project is pretty cool and thanks for your effort! 

We are looking for some solution to train models offline using Spark, yet score online in real time.   This is exactly what we need. 

I was trying to follow the minimal doc in the wiki page. https://github.com/combust-ml/mleap/wiki/Setting-up-a-Spark-2.0-notebook-with-MLeap-an-Toree

The page seems not finished yet.  Any unit test class of example that I can follow to use MLeap? 

Also, a couple of corrections. 
- page title should be "... MLeap and Toree"
- in build & install toree,  it should be "pip install toree-0.2.0.dev1.tar.gz"
- also,  it should be SPARK_HOME=... **jupyter toree install**

Again. Thanks!

**Comment by hollinwilkins** [comment]
Hello,

Glad to hear about your interest in MLeap. We are currently making a big push to get to version 0.3.0, which will get us much closer to a stable API to work with. We have 3 pull requests to get through and then we will release it to maven central. Over the next week, we will be building out documentation and examples about how to use MLeap.

Thank you for your patience, we'll check back in on this ticket as we build out the documentation.

**Comment by seme0021** [comment]
Hi @ltang ,

We checked in a few examples with both scala and pyspark - can you give them a try?
https://github.com/combust-ml/mleap-demo/tree/master/notebooks

We're working on getting a public model server up in the next few weeks so you can test .deploy() as well.

Best
M

**Comment by ltang** [comment]
Thanks. I'll have a try and get back to you in few days.

**Comment by lei-clari** [comment]
@seme0021 Thanks for the demos. 

I just walked through the airbnb example (except the deploy part). works out of the box!

I could not get toree to work due to some dependency conflict. May have to dig deeper. But the example works fine as long as I import all mleap dependencies. 

Several minor questions: 
1. why is the demo using MLeap's OneHotEncoder rather than Spark's default one? 
2. Is bundle.ml format simply a bundle of json files (node.json and model.json)?
3. Is TrueCar already using MLeap? 

Our own use case requires some additional transformers. Will check your source code to see whether we can add customized transformers.

**Comment by seme0021** [comment]
@lei-clari ,

We had to write our own OneHotEncoder because Spark’s uses metadata to perform the transformation. This is unusual for Spark models, so instead, we use a custom estimator/model which stores the size of the output vectors so we don’t need to rely on metadata to do one hot encoding.

Re bundle.ml: You can choose whether you want to serialize to json or to protobuf - your choice should depend on which transformers you’re using and which models you’re training (i.e. for tree-based models we recommend protofub). I’ll add documentation and an example of serialization to protobuf.

As far as TC, they were using it when we left, but have not stayed up to date on the latest usage there. If you’d like to talk with someone who’s running it in production we can make an intro.

Best
Mikhail

**Comment by hollinwilkins** [comment]
Hey, just giving an update here. We are building out comprehensive documentation for MLeap 0.5.0. You can see it here as it develops:

http://mleap-docs.combust.ml/

**Comment by geoHeil** [comment]
Inserting. Cool. Could you comment on how far you are with mleap and
sklearn integration.
Hollin Wilkins <notifications@github.com> schrieb am Di. 17. Jan. 2017 um
05:39:

**Comment by hollinwilkins** [comment]
@geoHeil I responded to this question in another thread, but I'll post here as well.

Here is a list of supported transformers: http://mleap-docs.combust.ml/core-concepts/transformers/support.html

We are coming out with Sklearn modules on PyPi with the next release of MLeap, 0.6.0, which should be a fairly quick release after 0.5.0.

**Comment by hollinwilkins** [comment]
@ltang We have added in pretty complete documentation here:
http://mleap-docs.combust.ml/

Please let us know in a separate issue if you would like us to add more specific documentation.

Cheers,
Hollin
