### ISSUE TITLE
MLeap should handle casting between data types

### ISSUE THREAD

**Issue by hollinwilkins** [combust/mleap#214]
Spark is able to cast data types to other data types. MLeap should support this as well so we can do things like:

1. Cast all inputs to the VectorAssembler as Doubles
2. Support multiple input types for the imputer

We how have access to the schema during transform, so we should be able to use the field data type and a target data type to produce a cast function with can be set as a selector when passing data in to be transformed.

**Comment by calinrc** [comment]
👍 

In particular VectorAssembler case I think the similar transformation can be done for all numeric types as the one performed for BigDecimal since vector assemble will always output a tensor of double types.
This can be done inline in model method without the schema feature being necessary in place

**Comment by hollinwilkins** [comment]
Closing this issue as it is now handled by automatic casting provided by MLeap.
