### ISSUE TITLE
Will you accept contributions?

### ISSUE THREAD

**Issue by darrenhaken** [combust/mleap#330]
Both myself and my company are interested in contributing to mleap for work we are doing deploying Spark ML models for real-time predictions.

First, will you accept PR's on the project/allow contributions?
Is there any form of guidelines/process you need?

I wanted to start looking at trying to support Spark SQL in mleap.

**Comment by hollinwilkins** [comment]
@darrenhaken Absolutely. Sorry for not getting back to this sooner. The SQLTransformer is an interesting one because it would require a SQL engine to execute. It's not an undoable task. I think this project offers a pluggable SQL engine: https://calcite.apache.org/

Let me know if you are more interested in pursuing this and let's talk more on gitter: https://gitter.im/combust/mleap

**Comment by darrenhaken** [comment]
Thanks for getting back to me, I'll head over to Gitter and we can start the conversation rolling.

Is there anywhere in the repo where I can see a roadmap of other features you're looking to add in the future e.g. more transformers etc?

**Comment by hollinwilkins** [comment]
@darrenhaken I will put a roadmap together and put it in the readme. Will close this issue and link you to it when I have.

**Comment by darrenhaken** [comment]
@hollinwilkins awesome! I'll close this off. FYI I'm heading off to vacation tomorrow so I'll head to Gitter when I'm back.
