### ISSUE TITLE
MLeap-spark does not support Spark 2.3

### ISSUE THREAD

**Issue by ludatabricks** [combust/mleap#363]
When I try to use MLeap-spark to serialize the pipeline with spark 2.3. It shows error "unsupported Spark version: ".
It seems that MLeap-spark does not support Spark 2.3 yet. 

Is there any plan to make MLeap support spark 2.3?

**Comment by cappaberra** [comment]
Interested in this as well.  Likely related to my inability to serialize a Spark Pipeline using Spark 2.3 since the above error is being masked by this one after calling serializeToBundle():

`Py4JJavaError: An error occurred while calling o2094.serializeToBundle.
: java.lang.NoClassDefFoundError: Could not initialize class org.apache.spark.ml.bundle.SparkBundleContext$`

I'm interested as well to know what it would take to support Spark v2.3.  Thanks!

**Comment by cappaberra** [comment]
In addition, this is a duplicate issue of this one:  https://github.com/combust/mleap/issues/352

**Comment by hollinwilkins** [comment]
#364 merged
