### ISSUE TITLE
Schema of the deployed model

### ISSUE THREAD

**Issue by davidkychen** [combust/mleap#38]
Hi,

I just tried mleap, which is really awesome. However, I was wondering is there a way to get the schema of the exported model in a format such as PMML? So that we can have a better overview of what types of features the model is using and information like that?

Thanks

**Comment by hollinwilkins** [comment]
Hey there,

This would be a great feature to have, and should be easy to implement. We actually had this in an earlier version as it is quite useful in certain instances. However, in order to accomplish it we needed to ensure that every transformer model knows the exact type of it's inputs and outputs. This is the case for most transformers with one notable exception: the VectorAssembler, which can actually take in Doubles or Vectors.

In order to circumvent this and come up with a schema to include in the Bundle.ML serialization, we have to pass the schema of the DataFrame used in training along with the transformer pipeline. We could include it as an optional file in the Bundle.ML if we are able to calculate the input schema, otherwise it would not be included.

**Comment by hollinwilkins** [comment]
We can include the optional DataFrame used to train the pipeline in the SparkBundleContext for this purpose: https://github.com/combust-ml/mleap/blob/master/mleap-spark/src/main/scala/org/apache/spark/ml/bundle/SparkBundleContext.scala

**Comment by hollinwilkins** [comment]
We still need to decide how to implement this. There are two options as I see it:
1. We add the data type to every socket so it's included with the node shape
2. We generate a separate file that is a mapping of socket name to the data type

**Comment by hollinwilkins** [comment]
It loos like tensorflow includes the data type in the argument definition. This makes sense, but will unfortunately introduce a breaking change.

In addition to this change, we will be making it so that we use the default OneHotEncoder provided by Spark and provide our estimator/model version in an extension library.

**Comment by hollinwilkins** [comment]
Okay, we are going to put type data into the sockets for the node shape. This, along with the children method, will allow us to calculate the minimum required input schema and the output schema of a Bundle.ML file.

**Comment by hollinwilkins** [comment]
Going to push this back to 0.6.0 to give some more time for thought on implementation. It would be nice to store a lot of meta information about the input/output data. For instance, Spark stores nominal values, ranges, mins, max, etc. We want to come up with a standard for storing this information that will work with Spark and Scikit-learn.

**Comment by hollinwilkins** [comment]
@ancasarb Do you still want to look at this one?

**Comment by ancasarb** [comment]
@hollinwilkins yes, if it's ok with you. I've started implementing the solution that we've talked about but haven't quite had the time to finish it off, I hope to be able to do that within the next few days.

**Comment by hollinwilkins** [comment]
@ancasarb Would be great to get your help with this. Just wanted to check because we will push this back to MLeap 0.8.0 or 0.7.1 if we want to get it out quicker.

**Comment by ancasarb** [comment]
@hollinwilkins sounds good to me.
