### ISSUE TITLE
Support spark.ml.tuning.CrossValidator and TrainValidationSplit

### ISSUE THREAD

**Issue by mengxr** [combust/mleap#389]
Those two tuning methods are used by Spark MLlib users to tune hyperparameters. It would be great if MLeap can support exporting them. It should be okay if we only export the bestModel selected, which may be already supported by MLeap.

**Comment by hollinwilkins** [comment]
*** Notes on this ***

This can be implemented using a `SimpleSparkOp` that delegates to the underlying model op to perform serialization to a subfolder called `best_model`.

The op name would be `cross_validator` and `train_validation_split`.

If we wanted to implement this where the underlying model ops are exposed instead of `cross_validator` and `train_validation_split`, we would have to add a parameter to the `opName` function in `OpModel`.

```
    def opName: String

    // would become
    def opName(obj: ModelType)
                         (implicit context: BundleContext[SparkBundleContext]): String
```

**Comment by ancasarb** [comment]
Closing this as PR has been merged.
