### ISSUE TITLE
 error: object OneHotEncoder is not a member of package org.apache.spark.ml.mleap.feature

### ISSUE THREAD

**Issue by cchung100m** [combust/mleap#443]
Hi all,
I am doing the official tutorial [mleap-demo](https://github.com/combust/mleap-demo/blob/master/notebooks/airbnb-price-regression.ipynb) but I encounter the import failed issue as below,  I am sure that I had already added the related packages from maven repo, can you share the experience on solving this kind of problem? Thank you.

System infromation:
> OS: CentOS Linux release 7.4.1708
> Spark version: 2.3.0.2.6.5.0-292
> Scala version: 2.11.8
> Java version: 1.8.0_131

```
./spark-shell  --packages ml.combust.mleap:mleap-spark_2.11:0.12.0,ml.combust.mleap:mleap-spark-extension_2.11:0.12.0,ml.combust.mleap:mleap-runtime_2.11:0.12.0,ml.combust.bundle:bundle-ml_2.11:0.12.0,com.jsuereth:scala-arm_2.11:2.0,com.databricks:spark-avro_2.11:3.0.1

scala> spark.sparkContext.listJars.foreach(println)
spark://localhost:44476/jars/ml.combust.mleap_mleap-spark_2.11-0.12.0.jar
spark://localhost:44476/jars/ml.combust.mleap_mleap-spark-extension_2.11-0.12.0.jar
spark://localhost:44476/jars/com.databricks_spark-avro_2.11-3.0.1.jar
spark://localhost:44476/jars/com.jsuereth_scala-arm_2.11-2.0.jar
spark://localhost:44476/jars/ml.combust.mleap_mleap-runtime_2.11-0.12.0.jar
spark://localhost:44476/jars/ml.combust.bundle_bundle-ml_2.11-0.12.0.jar

scala> import org.apache.spark.ml.mleap.feature.OneHotEncoder
<console>:23: error: object OneHotEncoder is not a member of package org.apache.spark.ml.mleap.feature
       import org.apache.spark.ml.mleap.feature.OneHotEncoder
              ^
```

**Comment by ancasarb** [comment]
in Spark 2.3, you can use org.apache.spark.ml.feature.OneHotEncoderEstimator instead. OneHotEncoder will be removed in future Spark versions.

**Comment by RayTsui** [comment]
@ancasarb Hi, actually I came cross this issue and have a question about OneHotEncoder/OneHotEncoderEstimator, which is, based on #220 and #443, how to distinguish the use of org.apache.spark.ml.feature.OneHotEncoderEstimator and org.apache.spark.ml.mleap.feature.OneHotEncoder. Because I use spark 2.3, there is no org.apache.spark.ml.mleap.feature.OneHotEncoder api, that means for spark before 2.3, we can use org.apache.spark.ml.mleap.feature.OneHotEncoder, for spark 2.3, instead, we need to use org.apache.spark.ml.feature.OneHotEncoderEstimator?
Thus, here I have to make myself clear about that. Thanks a lot.

**Comment by ancasarb** [comment]
Yes, so for Spark pre 2.3 you would use the ```org.apache.spark.ml.mleap.feature.OneHotEncoder``` transformer, and for Spark 2.3 you would use ```org.apache.spark.ml.feature.OneHotEncoderEstimator```. 

Just to let you know, starting 0.12.0, MLeap versions are tied to specific Spark versions, you can find more details here https://github.com/combust/mleap under "MLeap/Spark Version".
