### ISSUE TITLE
 Does dataframe of mleap preprocessing support sql?

### ISSUE THREAD

**Issue by jacksu** [combust/mleap#450]
Hi,

Like lending_club Demo.

In Offline, we process data as follow: 

val datasetFnl = spark.sqlContext.sql(f"""
    select
        loan_amount,
        fico_score_group_fnl,
        case when dti >= 10.0
            then 10.0
            else dti
        end as dti,
        emp_length,
        case when state in ('CA', 'NY', 'MN', 'IL', 'FL', 'WA', 'MA', 'TX', 'GA', 'OH', 'NJ', 'VA', 'MI')
            then state
            else 'Other'
        end as state,
        loan_title,
        approved
    from df
    where loan_title in('Debt Consolidation', 'Other', 'Home/Home Improvement', 'Payoff Credit Card', 'Car Payment/Loan',
    'Business Loan', 'Health/Medical', 'Moving', 'Wedding/Engagement', 'Vacation', 'College', 'Renewable Energy', 'Payoff Bills',
    'Personal Loan', 'Motorcycle')
""")

**In Online ,how can i do this?**

thanks.

**Comment by ancasarb** [comment]
Hi @jacksu,

SQL transformer isn't supported in MLeap, mostly because they could contain column based transformations (e.g. group by). 

What you can do is create custom transformers for the two case statements below, which you can use for training as well as scoring. 

```case when dti >= 10.0 then 10.0 else dti```
``` case when state in ('CA', 'NY', 'MN', 'IL', 'FL', 'WA', 'MA', 'TX', 'GA', 'OH', 'NJ', 'VA', 'MI') then state else 'Other'```

You can find some documentation on writing transformers below, please let me know if you need any additional help, happy to help!

http://mleap-docs.combust.ml/mleap-runtime/custom-transformer.html

**Comment by jacksu** [comment]
Hi @ancasarb 

I know, thanks.
