### ISSUE TITLE
[xgboost][databricks][scala] key not found xgboost.regression

### ISSUE THREAD

**Issue by changhiskhan** [combust/mleap#562]
Hi, I was wondering if this is a known issue or if I'm doing something obviously wrong.

I'm on a databricks runtime 5.4 ML cluster with a scala notebook. I'm essentially trying to reproduce one of the [mleap-xgboost-spark unit tests](https://github.com/combust/mleap/blob/master/mleap-xgboost-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/mleap/XGBoostRegressionModelParitySpec.scala) but it fails on `loadMleapBundle`.

I've ensured that the cluster has mleap-runtime and mleap-xgboost-runtime jars attached. The remaining dependencies should already be part of the databricks runtime.

Are there any scala examples showing how to use the mleap-xgboost integration from within a databricks notebook?

Thanks!

**Comment by mengxr** [comment]
@changhiskhan "xgboost.regression" is defined in `mleap-xgboost-runtime`, which is not part of the mleap assembly jar installed on Databricks. You can try the following workaround:

On a Databricks Runtime 5.5 ML cluster, install the following libraries:
* `com.jsuereth:scala-arm_2.11:2.0`
* `ml.combust.mleap:mleap-xgboost-runtime_2.11:0.13.0` excludes `ml.combust.mleap:mleap-runtime_2.11,ml.dmlc:xgboost4j`

Then at the top of your example notebook, run:

~~~scala
implicitly[ml.combust.mleap.runtime.MleapContext].bundleRegistry
  .register(new ml.combust.mleap.xgboost.runtime.bundle.ops.XGBoostRegressionOp)
~~~

It registers the `xgboost.regression` model with the default registry, which is used for serialization.

**Comment by changhiskhan** [comment]
Thanks @mengxr ! I will give this a shot asap.

**Comment by ancasarb** [comment]
hey @changhiskhan @mengxr apologies for the late response, there are two jars relating to xgboost: mleap-xgboost-runtime (that is used by mleap to do the scoring, and you can use this if you're actually building an MLeap pipeline) and mleap-xgboost-spark, this is the one you need to add in Databricks in order to use within Spark pipelines, it has all the necessary dependencies. Could you please give it a try and let me know if you still have issues?
