### ISSUE TITLE
Import broken with scikit-learn>=0.22

### ISSUE THREAD

**Issue by voganrc** [combust/mleap#617]
The `Imputer` class imported here:

https://github.com/combust/mleap/blob/beb4fd248e020282f10778c91d68a3518e981dcb/python/mleap/sklearn/extensions/data.py#L24

Was removed in scikit-learn version 0.22 as mentioned here:

https://github.com/scikit-learn/scikit-learn/blob/ee328faa3601b40944ad43e28bce71860d39f2de/sklearn/preprocessing/imputation.py#L60

**Comment by ancasarb** [comment]
At the moment, we have scikit-learn pinned to < 0.20, we would need to upgrade the scikit-learn version to get this working. Happy to work with you on doing this if you'd like!

**Comment by aaronzo** [comment]
I'm working in an environment where I need `scikit-learn>=0.22` and I get the error importing `Imputer` from the `preprocessing.data` module which I believe is the same. I 'hacked' a fix, namely I edited the `mleap/sklearn/preprocessing/data.py` file to have:
```
from sklearn.preprocessing import StandardScaler, MinMaxScaler, Binarizer, PolynomialFeatures
from sklearn.impute import SimpleImputer as Imputer
```
instead of the previous line importing `Imputer`. Does anyone know if this is likely to lead to trouble down the line?

Also, as an aside, as @ancasarb mentioned scikit is pinned to < 0.20, it would be useful if this was stated on the ['Getting Started with Sklearn' Documentation page.](https://mleap-docs.combust.ml/getting-started/scikit-learn.html)
