### ISSUE TITLE
featureImportances not serialized while serializing spark tree based models. Any resolution?

### ISSUE THREAD

**Issue by mtsol** [combust/mleap#729]

**Comment by mtsol** [comment]
@ancasarb ????

**Comment by mtsol** [comment]
do we need to write the serializer by ourselves or you guys are providing?

**Comment by ancasarb** [comment]
hey, apologies for the delay on this. i had a look and since this is not required for scoring, mleap won't serialize them. 

if needed, you could build a custom transformer that extends from the tree based models and also serializes the feature importances, or you could store those separately, given that as mentioned, they're not required for scoring.
