### ISSUE TITLE
Discrepancy in Spark predicted probabilities vs MLeap probabilites solved by changing memoryTimeout and diskTimeout

### ISSUE THREAD

**Issue by jwgwalton** [combust/mleap#732]
I've been building a container based on combustml/mleap-spring-boot:0.17.0-SNAPSHOT.

The container doesn't change any of the MLeap code, it just uses gsutil to pull a model down from GCS at runtime and then starts the Mleap server.

I was finding significant discrepancies in the magnitude of the predicted probabilities ( up to 0.036) between the spark model and the Mleap runtime version.

To deal with the model unloading itself after being idel for too long i updated from 

`"config":{"memoryTimeout":900000,"diskTimeout":900000},`

to 
`"config":{"memoryTimeout":525600000,"diskTimeout":525600000},`

The numerical error is gone. I have no understanding how this config change removed this error and it makes me very nervous. Does this control the memory allocated to the model aswell?

**Comment by ancasarb** [comment]
hey @jwgwalton,

thanks for raising the issue, would it be possible to understand a bit more about what type of model you are using? or have a trimmed down example that reproduces the error so that we can investigate more easily?

as you say, the memoryTimeout/diskTimeout wouldn't affect the scoring of the model, you can see their description here https://github.com/combust/bundle-protobuf/blob/master/mleap/mleap.proto#L108.

**Comment by jwgwalton** [comment]
@ancasarb Well this is embarassing. I can't seem to be able to replicate the discrepancies in the results. I obviously messed something up previously, apologies. I do have a question about int features being converted to floats in converting pyspark models to mleap, but i will open another issue. Cheers.
